#import "./UserContacts.gql"
#import "./UserLook.gql"
#import "./UserProfile.gql"
#import "./UserSkills.gql"
#import "./Self.gql"
fragment AllUserInfo on User {
    ...UserProfile
    ...Self
    ...UserContacts
    ...UserLook
    ...UserSkills
}
