# =============================================================================
# GRAPHQL SCHEMA
# Type definitions for Clients
# =============================================================================
#scalar _Template

# -----------------------------------------------------------------------------
# SUMMARY
# -----------------------------------------------------------------------------
#extend type Query {
#}

#extend type Mutation {
#}

#extend type Subscription {
#}


# -----------------------------------------------------------------------------
# TYPES
# -----------------------------------------------------------------------------

#type Template {
#    name: String! # translated virtual getter/setter using user's language
#    _: Localised_Template! # direct translations query/mutation
#}
#type Localised_Template {
#    name: LocalString!
#}

# -----------------------------------------------------------------------------
# INTERFACES
# -----------------------------------------------------------------------------


# -----------------------------------------------------------------------------
# APP SPECIFIC
# -----------------------------------------------------------------------------
