#import "./Self.gql"
#import "./UserContacts.gql"
#import "./UserDetails.gql"
#import "./UserSettings.gql"
#import "./UserSummary.gql"
fragment AllUserInfo on User {
    ...UserSummary
    ...UserDetails
    ...UserContacts
    ...UserSettings
    ...Self
}
