# =============================================================================
# GRAPHQL SCHEMA
# Type definitions for Clients
# =============================================================================
scalar Kg
scalar Km
scalar Cm
scalar Mm

# -----------------------------------------------------------------------------
# SUMMARY
# -----------------------------------------------------------------------------
#extend type Query {
#}

#extend type Mutation {
#}

#extend type Subscription {
#}


# -----------------------------------------------------------------------------
# TYPES
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# INTERFACES
# -----------------------------------------------------------------------------


# -----------------------------------------------------------------------------
# APP SPECIFIC
# -----------------------------------------------------------------------------
