version: '3.2'  # tested on Docker 18.04.0-ce, Compose version 1.20.1
services:
  database:
    image: mongo:4.0.16
    container_name: ${DB_HOST}
    hostname: ${DB_HOST}
    #restart: unless-stopped # enable this once all is working
    volumes:
      # mounting to host only works when using specific path (i.e. '/data/db', and not just '/data')
      - ./data/configdb:/data/configdb
      - ./data/db:/data/db

  server:
    build: ./  # directory of the Dockerfile
    container_name: ${SERVICE}
    hostname: ${SERVICE}
    #restart: unless-stopped # enable this once all is working
    links:
      - database:${DB_HOST}  # link this service to the database service
    depends_on:
      - database  # to ensure correct order of startup
    volumes:
      - ./uploads:/home/node/app/uploads
      - ./service:/home/node/app/service  # enable changing service variables without restarting server
    environment:
      NODE_ENV: production
    env_file:
      - .env
    expose:  # only available to linked services
      - ${API_PORT}
    ports:  # available to linked services and host machine
      - ${SOCKET_PORT}:${SOCKET_PORT}
    command: pm2 start index.js --name ${SERVICE} --no-daemon

networks:
  default:
    external:
      name: webproxy
