import { DISCONNECTED, ERROR, RESULT_SEPARATOR, SEPARATOR, SET, SUCCESS, TIMEOUT, UPDATE } from 'utils-pack'
import { actionTypeColor } from '../utils'

it(`${actionTypeColor.name}() returns correct color`, () => {
  expect(actionTypeColor(`TEST${SEPARATOR}${UPDATE}`)).toEqual('cyan')
  expect(actionTypeColor(`TEST${SEPARATOR}${SET}`)).toEqual('cyan')
  expect(actionTypeColor(`TEST${SEPARATOR}${SUCCESS}`)).toEqual('cyan')
  expect(actionTypeColor(`TEST${SEPARATOR}${ERROR}`)).toEqual('red')
  expect(actionTypeColor(`TEST${SEPARATOR}${TIMEOUT}`)).toEqual('yellow')
  expect(actionTypeColor(`TEST${SEPARATOR}${DISCONNECTED}`)).toEqual('yellow')
  expect(actionTypeColor(`TEST${SEPARATOR}${RESULT_SEPARATOR}${UPDATE}`)).toEqual('cyan')
  expect(actionTypeColor(`TEST${SEPARATOR}${RESULT_SEPARATOR}${SET}`)).toEqual('cyan')
  expect(actionTypeColor(`TEST${SEPARATOR}${RESULT_SEPARATOR}${SUCCESS}`)).toEqual('cyan')
  expect(actionTypeColor(`TEST${SEPARATOR}${RESULT_SEPARATOR}${ERROR}`)).toEqual('red')
  expect(actionTypeColor(`TEST${SEPARATOR}${RESULT_SEPARATOR}${TIMEOUT}`)).toEqual('yellow')
  expect(actionTypeColor(`TEST${SEPARATOR}${RESULT_SEPARATOR}${DISCONNECTED}`)).toEqual('yellow')
  expect(actionTypeColor(`TEST${RESULT_SEPARATOR}${UPDATE}`)).toEqual('cyan')
  expect(actionTypeColor(`TEST${RESULT_SEPARATOR}${SET}`)).toEqual('cyan')
  expect(actionTypeColor(`TEST${RESULT_SEPARATOR}${SUCCESS}`)).toEqual('cyan')
  expect(actionTypeColor(`TEST${RESULT_SEPARATOR}${ERROR}`)).toEqual('red')
  expect(actionTypeColor(`TEST${RESULT_SEPARATOR}${TIMEOUT}`)).toEqual('yellow')
  expect(actionTypeColor(`TEST${RESULT_SEPARATOR}${DISCONNECTED}`)).toEqual('yellow')
  expect(actionTypeColor(`TEST+${UPDATE}`)).toEqual('cyan')
  expect(actionTypeColor(`TEST+${SET}`)).toEqual('cyan')
  expect(actionTypeColor(`TEST+${SUCCESS}`)).toEqual('cyan')
  expect(actionTypeColor(`TEST+${ERROR}`)).toEqual('red')
  expect(actionTypeColor(`TEST+${TIMEOUT}`)).toEqual('yellow')
  expect(actionTypeColor(`TEST+${DISCONNECTED}`)).toEqual('yellow')
  expect(actionTypeColor(`TEST@${UPDATE}`)).toEqual('cyan')
  expect(actionTypeColor(`TEST@${SET}`)).toEqual('cyan')
  expect(actionTypeColor(`TEST@${SUCCESS}`)).toEqual('cyan')
  expect(actionTypeColor(`TEST@${ERROR}`)).toEqual('red')
  expect(actionTypeColor(`TEST@${TIMEOUT}`)).toEqual('yellow')
  expect(actionTypeColor(`TEST@${DISCONNECTED}`)).toEqual('yellow')
})
