# =============================================================================
# GRAPHQL SCHEMA
# Type definitions for Clients
# =============================================================================

# -----------------------------------------------------------------------------
# SUMMARY
# -----------------------------------------------------------------------------
#extend type Query {
#}

#extend type Mutation {
#}

#extend type Subscription {
#}


type Model {
    created: Timestamp!
    updated: Timestamp!
}
