version: '3'
# Last tested 14.02.2020 - working with nginx:1.17.8, Docker version 19.03.5, docker-compose version 1.20.1
services:
  nginx:
    image: nginx
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    # Note: `unless-stopped` option doesn't restart consistently on boot
    # Enable auto-restart once all is working
    #restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    # Enable auto-restart once all is working
    #restart: unless-stopped
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    # Enable auto-restart once all is working
    #restart: unless-stopped
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"
      #ACME_CA_URI: "https://acme-staging.api.letsencrypt.org/directory"
      #DEBUG: "true"

  # Add new websites steps:
  #   1. Update `WEBSITES_DOMAINS` in `.env` file
  #   2. Clone website repo to `WEBSITES_PATH`
  #   3. $ docker-compose up -d
  websites:
    image: nginx
    container_name: websites
    # Enable auto-restart once all is working
    #restart: unless-stopped
    expose:
      - "80"
      - "443"
    volumes:
      - ./websites/conf.d:/etc/nginx/conf.d
      - ${WEBSITES_PATH}:/var/www:ro
      - ${SERVERS_PATH}:/var/server:ro
    environment:
      VIRTUAL_HOST: ${WEBSITES_DOMAINS}
      LETSENCRYPT_HOST: ${WEBSITES_DOMAINS}
      LETSENCRYPT_EMAIL: ${WEBSITES_EMAIL}

networks:
  default:
    external:
      name: webproxy
